### ISSUE TITLE
virtualservice http.route timeout log error

### ISSUE THREAD

**Issue by wansuiye** [aspenmesh/istio-vet#39]
hi i met such error:
log:
```
E0121 07:13:56.601875       1 reflector.go:205] github.com/aspenmesh/istio-vet/vendor/github.com/aspenmesh/istio-client-go/pkg/client/informers/externalversions/factory.go:76: Failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList: Items: []v1alpha3.VirtualService: v1alpha3.VirtualService: Spec: v1alpha3.VirtualServiceSpec: VirtualService: Http: []*v1alpha3.HTTPRoute: v1alpha3.HTTPRoute: Timeout: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|timeout":"10s"}]}},{|..., bigger context ...|uster.local","port":{"number":8500}}}],"timeout":"10s"}]}},{"apiVersion":"networking.istio.io/v1alph|...
```

virtualservice:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: consul-proxy
spec:
  hosts:
  - proxy.infra.svc.cluster.local
  http:
  - timeout: 10s
    route:
    - destination:
        host: proxy.infra.svc.cluster.local
        port:
          number: 8500
```
thanks!
