### ISSUE TITLE
No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by esnible** [aspenmesh/istio-vet#40]
I use the IBM Kubernetes Service public cloud.

I invoked `istio-vet` like this:

```
docker run --rm -v ~/.bluemix/plugins/container-service/clusters/istio-test-paid3/kube-config-dal13-istio-test-paid3.yml:/root/.kube/config -v ~/.bluemix/plugins/container-service/clusters/istio-test-paid3/ca-dal13-istio-test-paid3.pem:/root/.kube/ca-dal13-istio-test-paid3.pem quay.io/aspenmesh/istio-vet:master
```

This failed with the message `No Auth Provider found for name "oidc"`.  The reason is that my configuration uses 

```
users:
- name: snible@us.ibm.com
  user:
    auth-provider:
      name: oidc
      config:
        client-id: kube
        client-secret: kube
        id-token: <10 lines of token code>
```
